In [42]:
import numpy as np

In [46]:
data = np.loadtxt('/Users/charlie/Downloads/BTTL1.band.pp.dat.gnu')  #path of .gnu file
split_data = np.hsplit(data, 2)
x_coord = np.unique(split_data[0])
y_coord = split_data[1]
rows = np.shape(x_coord)[0]
columns = np.shape(y_coord)[0] // rows
Y = y_coord.reshape(rows, columns)
final_data = np.insert(Y, 0, x_coord, axis=1)

In [47]:
Fermi = 3   #insert your fermi level

In [48]:
farry = np.zeros((rows,columns))

In [49]:
farry.fill(Fermi)

In [50]:
print(farry)

[[3. 3. 3. ... 3. 3. 3.]
 [3. 3. 3. ... 3. 3. 3.]
 [3. 3. 3. ... 3. 3. 3.]
 ...
 [3. 3. 3. ... 3. 3. 3.]
 [3. 3. 3. ... 3. 3. 3.]
 [3. 3. 3. ... 3. 3. 3.]]


In [51]:
np.insert(farry, 0, 0, axis=1)

array([[0., 3., 3., ..., 3., 3., 3.],
       [0., 3., 3., ..., 3., 3., 3.],
       [0., 3., 3., ..., 3., 3., 3.],
       ...,
       [0., 3., 3., ..., 3., 3., 3.],
       [0., 3., 3., ..., 3., 3., 3.],
       [0., 3., 3., ..., 3., 3., 3.]], shape=(31, 961))

In [52]:
fermi_data = np.insert(farry, 0, 0, axis=1) + final_data

In [45]:
np.savetxt('/Users/charlie/Downloads/BTTL1.band.csv',fermi_data,delimiter=',') #path to final data